version: '3.8'

services:
    db:
      image: postgres:16
      container_name: my_postgres
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: mypoatgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    app:
      build: .
      container_name: my_golang_app
      restart: always
      depends_on:
        - db
      environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_USER: admin
        DB_PASSWORD: admin
        DB_NAME: mypoatgres  # исправил на правильное имя БД
      ports:
        - "8080:8080"

volumes:
    postgres_data: